### ISSUE TITLE
Cannot find symbol com.google.mediapipe.modules.facegeometry.FaceGeometryProto.FaceGeometry

### ISSUE THREAD

**Issue by code-iot** [google/mediapipe#1208]
I was using the medapipe aar, in a separate android app. I was trying to get the face effect app. Looks like this (FaceGeometryProto) gets automatically generated. But I am not sure how. There were other such files (in mediapipe/framework/formats), which I could get it by updating mediapipe/framework/formats/BUILD. But not FaceGeometryProto. Can anybody help me ? When I tried other examples which is not using this specific class, I could get it working.

Mediapipe AAr file is generated using https://google.github.io/mediapipe/getting_started/android_archive_library.html

Can anybody help me ?

**Comment by jiuqiant** [comment]
[The mediapipe_aar rule](https://github.com/google/mediapipe/blob/8f69af91feb5944e130959dc9cc256b93d03abd2/mediapipe/java/com/google/mediapipe/mediapipe_aar.bzl) doesn't support face geometry yet. For generating the FaceGeometryProto, you need to 
1) Open up the visibility of the face geometry protos in [this BUILD file](https://github.com/google/mediapipe/blob/8f69af91feb5944e130959dc9cc256b93d03abd2/mediapipe/modules/face_geometry/protos/BUILD) like [this example](https://github.com/google/mediapipe/blob/8f69af91feb5944e130959dc9cc256b93d03abd2/mediapipe/framework/formats/BUILD#L224).
2) Add a _proto_java_src_generator rule like [this one](https://github.com/google/mediapipe/blob/8f69af91feb5944e130959dc9cc256b93d03abd2/mediapipe/java/com/google/mediapipe/mediapipe_aar.bzl#L83) for it.
3) List the generated java proto files in [this srcs field](https://github.com/google/mediapipe/blob/8f69af91feb5944e130959dc9cc256b93d03abd2/mediapipe/java/com/google/mediapipe/mediapipe_aar.bzl#L126).

**Comment by code-iot** [comment]
@jiuqiant Thank you very much for the quick response. I tried (2) and (3) already . Now I have made changes as (1) also. In both the cases I am getting following error when I tried to build aar

Could not make proto path relative: mediapipe/modules/face_geometry/protos/face_geometry.proto: No such file or directory

**Comment by code-iot** [comment]
Thank you very much. I tried (2) and (3), you have mentioned earlier. But that was giving error like "mediapipe/modules/face_geometry/protos/face_geometry.proto not found". Now I added (1) in your instruction and also filegroup. I am past the original issue now. I am hitting a different error, in building the aar file as it could not find other java classes. Let me try to solve that problem. But this issue is resolved. So, I am closing this issue.

Thanks once again. You are great.

**Comment by konovalov-k** [comment]
@code-iot Hi! Can you share your solution?
I did 1-3 steps. (I thought I did)
I modified [/mediapipe/java/com/google/mediapipe/mediapipe_aar.bzl](https://github.com/google/mediapipe/blob/8f69af91feb5944e130959dc9cc256b93d03abd2/mediapipe/java/com/google/mediapipe/mediapipe_aar.bzl#L83) (left) & [mediapipe/modules/face_geometry/protos/BUILD ](https://github.com/google/mediapipe/blob/8f69af91feb5944e130959dc9cc256b93d03abd2/mediapipe/modules/face_geometry/protos/BUILD)(right).
<img width="1403" alt="Screenshot 2020-11-11 at 14 22 14" src="https://user-images.githubusercontent.com/51828487/98805858-4d0eb280-2429-11eb-88e8-5907b60938b3.png">
And got this error.
<img width="1440" alt="Screenshot 2020-11-11 at 14 23 26" src="https://user-images.githubusercontent.com/51828487/98805956-792a3380-2429-11eb-922b-dd2d37ffff6e.png">
`FaceGeometryProto.java: No such file or directory`
@code-iot Have you ever faced this problem?

**Comment by Andrec-Dxs** [comment]
@konovalov-k did you manage to fix this issue? I managed to build the .aar for the face effect but with I still have the same error on Android Studio ("cannot find symbol ...... FaceGeometry")

**Comment by konovalov-k** [comment]
@Andrec-Dxs Yes. Share your code, image and let's see with what can I help.
P.S. My final mediapipe_aar.bzl & BUILD files [here](https://gist.github.com/konovalov-k/0e8318c7de296a2f3270bb435ce6a9d4).

**Comment by Andrec-Dxs** [comment]
Hey @konovalov-k 

Managed to fix the build issues. Now I'm having some issues regarding the models and how to import them.
I'm getting the following message:

com.google.mediapipe.framework.MediaPipeException: internal: Graph has errors: 
    Calculator::Open() for node "facegeometry__FaceGeometryPipelineCalculator" failed: ; could not read asset: geometry_pipeline_metadata.binarypbtil.cc:158) ; Failed to resolve path! Path = mediapipe/modules/face_geometry/data/geometry_pipeline_metadata.binarypb; Failed to read a metadata blob from file!; Failed to read the geometry pipeline metadata from file!
        at com.google.mediapipe.framework.Graph.nativeMovePacketToInputStream(Native Method)
        at com.google.mediapipe.framework.Graph.addConsumablePacketToInputStream(Graph.java:360)
        at com.google.mediapipe.components.FrameProcessor.onNewFrame(FrameProcessor.java:442)
        at com.google.mediapipe.components.ExternalTextureConverter$RenderThread.renderNext(ExternalTextureConverter.java:350)
        at com.google.mediapipe.components.ExternalTextureConverter$RenderThread.lambda$onFrameAvailable$0$ExternalTextureConverter$RenderThread(ExternalTextureConverter.java:295)
        at com.google.mediapipe.components.-$$Lambda$ExternalTextureConverter$RenderThread$IXJjtE68JMV2CMJNQcFYhTUqhj8.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at com.google.mediapipe.glutil.GlThread.run(GlThread.java:141)

**Comment by Andrec-Dxs** [comment]
@konovalov-k our files were exactly the same. Had some issues with Android Studio

**Comment by konovalov-k** [comment]
@Andrec-Dxs I got it from bazel-out folder (with search) after build faceeffect example and put it to assets folder inside project.

**Comment by Andrec-Dxs** [comment]
@konovalov-k can you please tell me which one?

<img width="305" alt="Screenshot 2020-11-30 at 14 22 12" src="https://user-images.githubusercontent.com/56541199/100621385-8430ff00-3317-11eb-980e-4f7b2fffdaf2.png">

**Comment by konovalov-k** [comment]
@Andrec-Dxs As I remember the one from android-release folder.
How it looks like in my proj.
<img width="403" alt="Screenshot 2020-11-30 at 17 40 17" src="https://user-images.githubusercontent.com/51828487/100623386-24e0e800-3333-11eb-8059-d7cf3445afa1.png">

**Comment by Andrec-Dxs** [comment]
@konovalov-k managed to fix this issue. Had to build the face_effect example app and access the bazel-out folder to get the .binarypb missing files

**Comment by AshishGaikwad** [comment]
> @Andrec-Dxs As I remember the one from android-release folder. How it looks like in my proj. <img alt="Screenshot 2020-11-30 at 17 40 17" width="403" src="https://user-images.githubusercontent.com/51828487/100623386-24e0e800-3333-11eb-8059-d7cf3445afa1.png">

can you share aar file with me. I am not able to create.
