### ISSUE TITLE
Support for EGL's drm/gbm platform for GPU inference on headless unix systems without a compositor

### ISSUE THREAD

**Issue by willstott101** [google/mediapipe#2489]
EGL from mesa (version 21) on our RPI 4s (OS is poky built with yocto) provides a "GBM platform" for rendering without a compositor like X or Wayland running. Rendering directly to displays without a compositor like this is simpler and faster for embedded applications.

However mediapipe currently doesn't work with the env var `EGL_PLATFORM=drm` as mesa's drm platform implementation doesn't support pbuffers. After browsing the source it seems like mediapipe doesn't use that pbuffer surface for anything except `eglMakeCurrent` which should be unnecessary (can use `EGL_NO_SURFACE` instead).

tflite also instantiates a pbuffer surface but I haven't yet dug deep enough to find out if it's neccessary or similarly pointless.

I'm opening this issue in-case anyone else comes across this problem with runtime errors like: `eglChooseConfig() returned no matching EGL configuration for RGBA8888 D16 ES3 request.`

By using `eglinfo` you can see in the `supported surfaces` section that mesa's GBM platform only supports `win` but x11 supports `win,pb,pix`

BTW nvidea's non-free drivers support `pb,str` in their device platform so switching to window surfaces instead of pbuffer surfaces would be non-portable.

**Comment by sgowroji** [comment]
Hi @willstott101, Which MediaPipe solution are you referring to the above issue. And could you please provide the steps. Thanks!

**Comment by sgowroji** [comment]
Duplicate https://github.com/google/mediapipe/issues/1483

**Comment by willstott101** [comment]
During my testing I am using a `.so` library of mediapipe to run a graph based on the `face_detection` module.

I'm not sure if this is a duplicate - I have asked in #1483 if they can use `eglinfo` to determine if lack of pbuffer support is indeed the problem for them.

**Comment by willstott101** [comment]
See: https://github.com/google/mediapipe/pull/2608 which makes EGL on GBM work for me on ubuntu - both with nvidea drivers and with intel integrated with mesa. i.e. `EGL_PLATFORM=gbm` allows mediapipe to use the GPU without X or Wayland available.

**Comment by willstott101** [comment]
Keep in mind that if you have X or Wayland running you don't need to use this. This actually falls back to CPU when I try to use it with nvidea non-free drivers on my dev PC. However, running without `EGL_PLATFORM` specified at all works perfectly still, even with the patch.

**Comment by pkoppise** [comment]
I20211109 06:26:59.582561  1483 demo_run_graph_main_gpu.cc:58] Initialize the calculator graph.
I20211109 06:26:59.592662  1483 demo_run_graph_main_gpu.cc:62] Initialize the GPU.
libEGL warning: invalid EGL_PLATFORM given
I20211109 06:26:59.615502  1483 gl_context_egl.cc:163] Successfully initialized EGL. Major : 1 Minor: 4
W20211109 06:26:59.615597  1483 gl_context_egl.cc:168] Creating a context with OpenGL ES 3 failed: UNKNOWN: ; eglChooseConfig() returned no matching EGL configuration for RGBA8888 D16 ES3 request. 
W20211109 06:26:59.615622  1483 gl_context_egl.cc:169] Fall back on OpenGL ES 2.
E20211109 06:26:59.616672  1483 demo_run_graph_main_gpu.cc:197] Failed to run the graph: ; eglChooseConfig() returned no matching EGL configuration for RGBA8888 D16 ES2 request.

I am facing above issue when running hand_tracking_gpu example on RPI4(webOSE).

Could you please let me know on how to resolve the issue? 

Note:
root@raspberrypi4:/home/root# opkg list-installed | grep -i mesa
libegl-mesa - 2:20.0.2-r0webos6webosrpi4
libgles2-mesa - 2:20.0.2-r0webos6webosrpi4
mesa-megadriver - 2:20.0.2-r0webos6webosrpi4

**Comment by willstott101** [comment]
Have you tried applying #2608 ?

**Comment by pkoppise** [comment]
I did not apply the patch 2608 ..will make changes and share the output..thanks for the reply @willstott101

**Comment by willstott101** [comment]
Also `libEGL warning: invalid EGL_PLATFORM given` is suspicious. Are you running with a `EGL_PLATFORM=` envvar? The patch at #2608 is only relevant if you're trying to run on a headless pi without x11

**Comment by pkoppise** [comment]
Guess I am running the headless pi without x11 (i am not sure), but DISTRO  does not contain feature x11

root@raspberrypi4:/home/root# 
root@raspberrypi4:/home/root# export EGL_PLATFORM=wayland
root@raspberrypi4:/home/root# /usr/bin/hand_tracking_gpu --calculator_graph_config_file=mediapipe/graphs/hand_tracking/hand_tracking_desktop_live_gpu.pbtxt
E20211109 07:39:03.635126  1664 demo_run_graph_main_gpu.cc:197] Failed to run the graph: ; eglChooseConfig() returned no matching EGL configuration for RGBA8888 D16 ES2 request. 
root@raspberrypi4:/home/root# 
root@raspberrypi4:/home/root# 
root@raspberrypi4:/home/root# export EGL_PLATFORM=x11
root@raspberrypi4:/home/root# /usr/bin/hand_tracking_gpu --calculator_graph_config_file=mediapipe/graphs/hand_tracking/hand_tracking_desktop_live_gpu.pbtxt
E20211109 07:39:25.714164  1673 demo_run_graph_main_gpu.cc:197] Failed to run the graph: ; Unable to initialize EGLpipe/gpu/gl_context_egl.cc:162) 
root@raspberrypi4:/home/root#

**Comment by pkoppise** [comment]
1) Applied patch 
2)  "export EGL_PLATFORM=wayland"
3) GLOG_logtostderr=1 /usr/bin/hand_tracking_gpu --calculator_graph_config_file=mediapipe/graphs/hand_tracking/hand_tracking_desktop_live_gpu.pbtxt  --outpu
t_video_path=hand_gpu.avi

o/p: no errors 

I20211109 08:18:04.479142  1725 demo_run_graph_main_gpu.cc:58] Initialize the calculator graph.
I20211109 08:18:04.489197  1725 demo_run_graph_main_gpu.cc:62] Initialize the GPU.
I20211109 08:18:04.511878  1725 gl_context_egl.cc:164] Successfully initialized EGL. Major : 1 Minor: 4
I20211109 08:18:04.515290  1730 gl_context.cc:331] GL version: 3.1 (OpenGL ES 3.1 Mesa 20.0.2)
I20211109 08:18:04.515565  1725 demo_run_graph_main_gpu.cc:68] Initialize the camera or load the video.
I20211109 08:18:05.120087  1725 demo_run_graph_main_gpu.cc:89] Start running the calculator graph.
I20211109 08:18:05.122112  1725 demo_run_graph_main_gpu.cc:94] Start grabbing and processing frames.
INFO: Created TensorFlow Lite delegate for GPU.
I20211109 08:18:07.475373  1725 demo_run_graph_main_gpu.cc:171] Prepare video writer.


But the size of file is 0KB...(need to check once)..

Thanks a lot for your help.

**Comment by pkoppise** [comment]
I20211109 10:26:57.418800  1775 demo_run_graph_main_gpu.cc:58] Initialize the calculator graph.
I20211109 10:26:57.428886  1775 demo_run_graph_main_gpu.cc:62] Initialize the GPU.
I20211109 10:26:57.451319  1775 gl_context_egl.cc:164] Successfully initialized EGL. Major : 1 Minor: 4
I20211109 10:26:57.454751  1780 gl_context.cc:331] GL version: 3.1 (OpenGL ES 3.1 Mesa 20.0.2)
I20211109 10:26:57.455013  1775 demo_run_graph_main_gpu.cc:68] Initialize the camera or load the video.
I20211109 10:26:58.396498  1775 demo_run_graph_main_gpu.cc:89] Start running the calculator graph.
I20211109 10:26:58.399134  1775 demo_run_graph_main_gpu.cc:94] Start grabbing and processing frames.
INFO: Created TensorFlow Lite delegate for GPU.
I20211109 10:27:01.037875  1775 demo_run_graph_main_gpu.cc:171] Prepare video writer.
I20211109 10:27:28.187114  1775 demo_run_graph_main_gpu.cc:186] Shutting down.
I20211109 10:27:28.303120  1775 demo_run_graph_main_gpu.cc:200] Success!

Now able to save the video output..when playing the video, no graph is rendered at hand (left and right)....could you please let me know what could be the issue?

**Comment by pkoppise** [comment]
@willstott101 

a) generated libmediapipe.so for gpu (hand_tracking example) , included the patch https://github.com/google/mediapipe/pull/2608   as i am using RPI4 (webos) with Wayland - EGL
b) Used the lib in Qt/QML project
c) Compilation is good, ipk generated, insatlled ipk, rebooted the device
After launching the application got below logs

Adding screen 0xed3820 for wl_output 17 with displayId of "0" details: "display_id=0&name=HDMI1" true
Using Wayland-EGL
WARNING: Logging before InitGoogleLogging() is written to STDERR
I20211111 03:07:51.709959  1449 gl_context_egl.cc:164] Successfully initialized EGL. Major : 1 Minor: 4


Looks like surface is not created

Could you please let me know what might be the issue? 
Note: I was able to run the handtracking cpu example as a Qt/QML application on webos /RPI4

**Comment by pkoppise** [comment]
Hi @willstott101 

I have created lib mentioned in https://github.com/willstott101/meta-mediapipe/blob/master/recipes-framework/mediapipe/files/0002-Build-library.patch  and using it in my QT project on RPI4 (wayland display)...But I got same error, which was mentioned earlier  

W20211109 06:26:59.615597 1483 gl_context_egl.cc:168] Creating a context with OpenGL ES 3 failed: UNKNOWN: ; eglChooseConfig() returned no matching EGL configuration for RGBA8888 D16 ES3 request.
W20211109 06:26:59.615622 1483 gl_context_egl.cc:169] Fall back on OpenGL ES 2.
E20211109 06:26:59.616672 1483 demo_run_graph_main_gpu.cc:197] Failed to run the graph: ; eglChooseConfig() returned no matching EGL configuration for RGBA8888 D16 ES2 request.

I have applied patch (https://github.com/google/mediapipe/pull/2608) , but performance is not that good compared to CPU, but CPU load is reduced 4 times.

Could you please let me know how to run the GPU version on RPI4 with way-land surface ?

**Comment by willstott101** [comment]
I _think_ in some circumstances you may end up emulating the GPU which makes it crazy slow. Have you tried different `EGL_PLATFORM` values including `EGL_PLATFORM=wayland` and `EGL_PLATFORM=gbm` (works independently of compositor) at runtime? I haven't ever tried using wayland with mediapipe or egl for that matter - we use x11 still atm

**Comment by willstott101** [comment]
Ah you say your CPU load was reduced? We've had a lot of trouble on RPi 4 with it's memory bus - shifting too much memory around can saturate it (when you're rendering and mediapiping and capturing cameras etc). I think you might have to dig around to figure out how to improve the performance. Try turning off other programs and reducing camera resolution and such - mediapipe's examples don't need very big frame sizes.

**Comment by pkoppise** [comment]
> I _think_ in some circumstances you may end up emulating the GPU which makes it crazy slow. Have you tried different `EGL_PLATFORM` (env var at runtime) values including `EGL_PLATFORM=wayland` and `EGL_PLATFORM=gbm` (works independently of compositor)? I haven't ever tried using wayland with mediapipe or egl for that matter - we use x11 still atm

@willstott101 thanks for reply.

Yes, CPU load is reduced when running hand tracking example using gpu (30%) , with out using GPU the cpu load is 120%. Yes, we will spend more time on improving the performance(enabling Dma-Buf Zero copy for better video rendering, threadpool etc..)

On other hand tried setting the variable EGL_PLATFORM for supported surfaces, still patch dependency is there.

Could you please let me know, on how do check application is using GPU or emulating it?

**Comment by tuotuoshao** [comment]
Hi @willstott101 ，what i want is to run gpu examples in a docker which works on my headless server host. Obviously, I've to run the examples in my host firstly，and i've made a lot of efforts to achieve it including reset my nvidia drivers and reload nvidia_drm  after referencing to your answers，thank you!
       I've understood what I need is the GBM platform, and in my host the command eglinfo outputs normally，the "EGL vendor string" under the GBM platform is NVIDIA，but in the docker，this value is  Mesa Project.  I've been experimented  of that if this  string isn't NVIDIA, the processing speed becomes slowly, however, i have to guarantee the FPS.
     For the docker，I used the nvidia/opengl docker and ran with --privileged --gpus parameters，here is the message:
![飞书20220225-115816](https://user-images.githubusercontent.com/51219602/155651052-a82fc94c-b4af-4574-beb8-cbe1454d8410.png)
Changing the docker tag，the message may like this
![飞书20220225-120031](https://user-images.githubusercontent.com/51219602/155651331-87c14fc2-199c-4df2-8b97-5dab5ec69dee.png)
Anyway，the string isn't NVIDIA，can you help me？

**Comment by willstott101** [comment]
https://github.com/ehfd/docker-nvidia-egl-desktop ?

**Comment by tuotuoshao** [comment]
Hi，I've built mesa from source code but it didn't solve this problem.
And I find the import librarys libnvidia-eglcore.so and libnvidia-egl-gbm.so in /usr/lib/x86_64-linux-gnu/ in my host server，but in the nvidia' dockers，i can only find libnvidia-eglcore.so, there's no libnvidia-egl-gbm.so, I guess that's the problem. But these two files come from my nvidia driver, how could i get these files in my docker?

**Comment by willstott101** [comment]
I'm afraid I haven't tried using Mediapipe in a container yet - you're probably better off asking in those `docker-nvidea` repos if you've got to the point of knowing which lib seems to be missing.

**Comment by tuotuoshao** [comment]
Okay, thanks.

**Comment by kuaashish** [comment]
@willstott101,

Are you still looking for this feature to be implemented? We believe implementation requires significant engineering effort And having other priorities ahead. However, Upgraded solutions will be supporting the Raspberry PI soon and will let you once it becomes available.

**Comment by willstott101** [comment]
I have fixed it in #2608 - we've been running with that patch applied

**Comment by kuaashish** [comment]
@willstott101,

This is a legacy solution And We will be not able to merge this request. Thank you

**Comment by kuaashish** [comment]
@willstott101,

This PR belongs to the older legacy solution And We are not accepting the PR request, Will not be able merging the request. 
We request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions. Thank you

**Comment by richtertang** [comment]
**Update: We've solved this for the MediaPipe Tasks API (Python) on ARM Mali GPU.**

First, thanks to @willstott101 for PR #2608 — it correctly identified the root cause. For those finding this closed issue via search: the problem **still exists** in the current Tasks API (v0.10.x). Google closed this issue because the PR targeted the legacy C++ graph API, but `GlContextEgl` still calls `eglGetDisplay()` + requires pbuffer surfaces in the Tasks SDK.

#### Root cause (still present in v0.10.35)

`mediapipe/gpu/gl_context_egl.cc` uses `eglGetDisplay(EGL_DEFAULT_DISPLAY)`, which on Mesa GBM platform returns an EGL display that **doesn't support pbuffer surfaces**. The subsequent `eglChooseConfig()` for `EGL_PBUFFER_BIT` returns zero configs → `eglCreatePbufferSurface()` fails → GPU initialization aborts.

On ARM Mali (Rockchip libmali), the proprietary driver supports GBM via `EGL_PLATFORM_GBM_KHR` but **only exposes window surfaces** (same as Mesa DRM). So both open-source (Mesa) and proprietary (libmali) GBM implementations have this pbuffer gap.

#### Our fix

We patched `gl_context_egl.cc` to use `eglGetPlatformDisplay(EGL_PLATFORM_GBM_KHR, gbm_device, NULL)` instead of `eglGetDisplay()`, then create a minimal GBM surface wrapper to satisfy the pbuffer requirement. The key changes:

1. **Platform detection**: At EGL init, probe for `/dev/dri/renderD128` + `gbm_create_device()` to detect GBM availability
2. **Display creation**: `eglGetPlatformDisplay(EGL_PLATFORM_GBM_KHR, gbm_device, NULL)` instead of `eglGetDisplay()`
3. **Surface workaround**: Since GBM doesn't support `EGL_PBUFFER_BIT` in `eglChooseConfig()`, we add `EGL_WINDOW_BIT` to the config attribs and create a dummy GBM surface instead of a pbuffer
4. **No X11 dependency**: The entire init path requires no DISPLAY env var, no X server, no Xvfb

This runs **without any display/compositor** — pure DRM/KMS + GBM.

#### Benchmark (FaceLandmarker with blendshapes, RK3576 Mali-G52 MC3)

| Config | Avg/frame | FPS | Speedup |
|--------|-----------|-----|---------|
| CPU (XNNPACK), headless | 33.4 ms | 29.9 | 1.0x |
| **GPU (GBM), headless** | **14.4 ms** | **69.2** | **2.3x** |
| GPU (GBM), X11 (:0) | 14.8 ms | 67.4 | 2.3x |

- 720p video, 60 frames, `num_faces=1`, `output_face_blendshapes=True`
- GPU GBM headless ≈ GPU X11 (difference < 3%) — no performance penalty for running without X11
- Tested on Rockchip RK3576 (Mali-G52 MC3, libmali g13p0), Ubuntu 22.04 aarch64, Python 3.12

#### Docker / headless deployment advantage

Since GBM headless needs no X11/Wayland, Docker deployment only requires mapping `/dev/dri/renderD128` — no X11 socket passthrough, no Xvfb, no `DISPLAY` env var. This is a significant operational advantage for production edge deployments.

#### What we're sharing

We have a working aarch64 Python wheel (v0.10.35) with these patches. We're preparing a technical writeup and considering submitting a PR for the Tasks API. Happy to collaborate with anyone working on similar EGL/headless issues on other platforms (Jetson, RPi 5, etc.).

**Platforms verified**: RK3576 (Mali-G52 MC3). Theoretically applicable to: RK3588 (Mali-G610), RK3568 (Mali-G52), any ARM Mali with GBM support.

**Not yet tested**: Jetson (`EGL_EXT_platform_device` would be needed instead of `EGL_PLATFORM_GBM_KHR`), RPi 5 (VideoCore VII, V3D driver — different EGL stack).

  **Terminal demo** (headless GPU on RK3576 Mali-G52):
  https://asciinema.org/a/Mv4LEGvaroBSs6oJ
