### ISSUE TITLE
windows10 compile aar failure 

### ISSUE THREAD

**Issue by ylj318** [google/mediapipe#3786]
engineer:
i used  follow command
<em>bazel build -c opt --linkopt="-s" --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --fat_apk_cpu=arm64-v8a,armeabi-v7a 
//mediapipe/examples/android/src/java/com/google/mediapipe/apps/hair_aar_example:"hair_segmentation_aar"<em>

installed :
opencv 3.4.16 (c:\opencv) 
(D:\bazel) bazel 5.3.1
ANDROID_HOME=D:\Android\sdk
ANDROID_NDK_HOME=D:\Android\sdk\ndk\21.0.6113669

add
"android_sdk_repository(name = \"androidsdk\", path = \"D:\\Android\\sdk\")" 
"android_ndk_repository(name = \"androidndk\", api_level=21, path = \"D:\\Android\\sdk\\ndk\\21.0.6113669\")" 
into file of d:\mediapipe\workspace

reponse error :

ERROR: D:/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/hair_aar_example/BUILD:3:14: While resolving toolchains for target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/hair_aar_example:hair_segmentation_aar_android_lib: no matching toolchains found for types @bazel_tools//tools/android:sdk_toolchain_type
ERROR: Analysis of target '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/hair_aar_example:hair_segmentation_aar' failed; build aborted:
INFO: Elapsed time: 0.226s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)

thanks very much

**Comment by kuaashish** [comment]
Hi @ylj318,
Could you confirm that you are able to build MediaPipe as mentioned in the official [documentation](https://google.github.io/mediapipe/getting_started/install.html#installing-on-windows). If yes, then please build using the below android target as mentioned in the [documentation](https://google.github.io/mediapipe/solutions/hair_segmentation.html#mobile):

`mediapipe/examples/android/src/java/com/google/mediapipe/apps/hairsegmentationgpu:hairsegmentation`

Please let us know if this resolves the issue. Thank you!

**Comment by ylj318** [comment]
@kuaashish 
how do you do.
thanks for your response.  the problem was solved on centos8.
but used in android run in mobile , error found "java.lang.RuntimeException: java.io.FileNotFoundException: mobile_gpu.binarypb"
i cann't find the file in compile folder of aar

**Comment by kuaashish** [comment]
Hi @ylj318,
Did you try to run the above [android target](https://github.com/google/mediapipe/issues/3786#issuecomment-1291755897) on the command prompt in the windows? As mentioned in the [documentation](https://google.github.io/mediapipe/getting_started/install.html#installing-on-windows) MediaPipe Android apps is still not possible on native Windows. Instead, Please build the MediaPipe solution in the Android studio mentioned in the [documentation](https://google.github.io/mediapipe/getting_started/android_solutions.html#building-solution-example-apps). Thank you!

**Comment by ylj318** [comment]
@kuaashish 
thank you ,
i took the file of 'mobile_gpu.binarypb' .
