### ISSUE TITLE
[tasks-vision] ReferenceError: self is not defined

### ISSUE THREAD

**Issue by arghideutis** [google/mediapipe#4800]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

No

### OS Platform and Distribution

Ubuntu 22.04

### Programming Language and version

Typescript

### Solution

Pose

### Describe the actual behavior

Importing @mediapipe/tasks-vision module leads to an error

### Describe the expected behaviour

Should import the module

### Standalone code/steps you may have used to try to get what you need

```shell
In SvelteKit 1.20.4:

import { FilesetResolver, PoseLandmarker } from "@mediapipe/tasks-vision";

const vision = await FilesetResolver.forVisionTasks(
      "https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision/wasm"
    );

const poseLandmarker = await PoseLandmarker.createFromOptions(vision, {
            baseOptions: {
                modelAssetPath: `https://storage.googleapis.com/mediapipe-models/pose_landmarker/pose_landmarker_lite/float16/1/pose_landmarker_lite.task`,
                delegate: "GPU"
            },
            runningMode: "VIDEO",
        });
```

### Other info / Complete Logs

```shell
7:23:29 AM [vite] Error when evaluating SSR module /src/lib/detection/video/PoseLandmarkDetector.ts: failed to import "@mediapipe/tasks-vision"
 |- ReferenceError: self is not defined
     at file:///app/node_modules/@mediapipe/tasks-vision/vision_bundle.mjs:1:7
     at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
```

**Comment by schmidt-sebastian** [comment]
This seems like something you should be able to fix by configuring Svelte. See how this problem is supposed to be fixed for `window`: https://www.okupter.com/blog/sveltekit-window-is-not-defined

`self` should exist almost everywhere: https://developer.mozilla.org/en-US/docs/Web/API/Window/self, so I don't think this is something we can fix.

**Comment by lc-spxl** [comment]
I guess what happens in Svelte (and other framework) is server side rendering. 

What you suggest is correct, however not practically feasible. 

The `self` error happens after an `import` of the mediapipe library, not in user code.

**Comment by schmidt-sebastian** [comment]
We have yet to build the testing infrastructure to ensure that our libraries work for Servers/Node. This is already in our backlog. Will hopefully get to this soon.

**Comment by schmidt-sebastian** [comment]
Marking this as a feature request.

**Comment by akanshSirohi** [comment]
Same issue I faced when I updated my NextJS latest v13.5.4
My OS: Windows 11

![image](https://github.com/google/mediapipe/assets/34837239/21b38868-a522-4512-838c-2e5beb602b53)

**Comment by mattkenefick** [comment]
Similar:

```
 FAIL  test/unit/Comment.spec.ts
  ● Test suite failed to run

    ReferenceError: self is not defined

      at Object.<anonymous> (node_modules/@mediapipe/tasks-vision/vision_bundle.cjs:1:157)
```

**Comment by rahul3v** [comment]
I find the same issue in  v10.0.7
So I am using v0.10.4 for now (as not causing this issue)

**Comment by schmidt-sebastian** [comment]
We changed our build process with 0.10.5 onwards, which resulted in a much smaller binary size. I am asking around internally if there is a way to not use `self` directly.

**Comment by schmidt-sebastian** [comment]
This should be fixed in the next release. You can get a nightly build by installing https://www.npmjs.com/package/@mediapipe/tasks-vision/v/0.0.0-nightly-20231023

**Comment by schmidt-sebastian** [comment]
Hm - that version seems to be broken. Will report back when we have a fix.

**Comment by schmidt-sebastian** [comment]
`0.0.0-nightly-20231024` is working and contains the fix.

**Comment by SupaSibs** [comment]
hey @schmidt-sebastian seems that the version is still broken:
ReferenceError: document is not defined
this probably isnt an error with the version but maybe node is making document not work on downloaded packages

**Comment by c4b4d4** [comment]
> ReferenceError: document is not defined

I'm having this same problem with the latest version. I'm running it inside a web worker.

**Comment by andypotato** [comment]
I am running into the same issue  - getting "ReferenceError: document is not defined" when trying to run any vision task inside nodejs

**Comment by schmidt-sebastian** [comment]
You might be running into this issue because of this: 
https://github.com/google/mediapipe/blob/bb4906bcd36513bd3ba6d948bf98f561a869626b/mediapipe/web/graph_runner/run_script_helper.ts.template#L15

Can you check if https://github.com/JamesJansson/importScripts helps?

**Comment by dbaynard** [comment]
I confirm 0.10.8 works.

@schmidt-sebastian Did you reopen because of the `document is not defined` error, or something else?

**Comment by andypotato** [comment]
@schmidt-sebastian if necessary I can provide some minimal example to reproduce the `document is not defined` error but it seems plausible the issue is related to `importScripts` as you suspect. I will find some time later today to try if your suggested fix works and report back

Thank you for looking into it!

**Comment by dbaynard** [comment]
Actually it seems that 0.10.8 is broken, for me — I'll have to gather error messages to see what has happened (the impact is vision loads but doesn't run).

I can use 0.10.6, though; the error that led me to this thread seemed to go away by itself, and I'm not sure why.

I suspect the `document is not defined` error is something else, given code expecting `document` should run in a browser, and code expecting `self` has probably been designed to run in a worker, right?

**Comment by andypotato** [comment]
So just to clarify, @mediapipe/tasks-vision is not meant to be run in a nodejs environment?

**Comment by wasimsafdar** [comment]
> vision
I am still getting an error "document is not defined" after trying your solution. I wanted to run this code on server side so that it will not be visible to client.

**Comment by schmidt-sebastian** [comment]
We currently only support browser environments and don't have testing infrastructure that can validate that our libraries work in Node. I will try to make this work though.

**Comment by SupaSibs** [comment]
ah i see thanks

**Comment by davidstrahm** [comment]
Getting the same `document is not defined` error when running tasks-vision inside a webworker. Works outside of webworker.

Version 0.10.9.
